### ISSUE TITLE
Sharing functionality

### ISSUE THREAD

**Issue by OlkaA** [HackYourFuture-CPH/FP-annotatetheweb-class10#206]
Add 'someId' to the path '/projects/:someId' (could be screenshot Id)

Include sharing functionality from storybook to the menu and the project page

**Comment by laila1222** [comment]
Subtasks: 

- [x] - change the color of menus in sidemenubar, only the active menus should be white
- [x] - When clicking on sharing menu, sharing dialog should appear

- [x] when clicking somewhere else, dialog should disappear

- [x] - Sharing link from dialog
- [x] - screenshot_id is in local storage, use that for the link
- [x] get screenshots from url not from local storage

- [x] Make that link only contains one parameter: so annotations are connected to screenshot_key instead of id. Or change screenshot Id to string in db, have the same value as key.

**Comment by laila1222** [comment]
Done, merged
